/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab8;

import java.awt.BorderLayout;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MALAK
 */
public class Admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin.class.getName());

    /**
     * Creates new form Admin
     */
     private User cu;
    public Admin() {
        initComponents();
    }
    
    public Admin(User u)
    {
     this.cu=u;
      initComponents();
    }
    private void loadAllCoursesIntoTable(JsonDataBaseManager db) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // clear old rows

    try
    {
    ArrayList<Course> allCourses = db.getAllCourses1();

    for (Course c : allCourses) {
        model.addRow(new Object[]{
            c.getCourseId(),
            c.getTitle(),
            c.getInstructorId(),
            c.getApproval_status()
        });
    }
    }
    catch(IOException e){
     JOptionPane.showMessageDialog(this,"Error loading courses");
    }
}
    private void loadPendingCoursesIntoTable(JsonDataBaseManager db) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // clear old rows

    try
    {
    ArrayList<Course> pendingCourses = db.loadpendingcourses();

    for (Course c : pendingCourses) {
        model.addRow(new Object[]{
            c.getCourseId(),
            c.getTitle(),
            c.getInstructorId(),
            c.getApproval_status()
        });
    }
    }
    catch(IOException e){
     JOptionPane.showMessageDialog(this,"Error loading courses");
    }
}
    private void loadLessonsForCourse(String courseId) {
    // Find the course by ID from your database
    JsonDataBaseManager db = new JsonDataBaseManager();
    try{
   // ArrayList<Course> pendingCourses = db.loadpendingcourses();
     ArrayList<Course> allCourses = db.getAllCourses1();

    for (Course c : allCourses) {
        if (c.getCourseId().equals(courseId)) {
            // Now you can display lessons in another table, panel, or dialog
            for (Lesson lesson : c.getLessons()) {
                System.out.println("Lesson: " + lesson.getTitle());
                // Or populate another JTable with lesson details
            }
        }
    }
    }
    catch(IOException e){
     JOptionPane.showMessageDialog(this,"Error loading courses");
    }
}

private void refreshTable(ArrayList<Course> courses) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    for (Course c : courses) {
        model.addRow(new Object[]{
            c.getCourseId(),
            c.getTitle(),
            c.getInstructorId(),
             c.getApproval_status()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Id", "Title", "Instructor Id", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("review");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All courses", "Pending courses" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("filter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Review", jPanel1);

        jButton1.setText("log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login studentFrame = new login();
        studentFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
 
        /*int selectedRow = jTable1.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Select a course first!");
    return;
}

DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
String courseId = (String) model.getValueAt(selectedRow, 0);

JsonDataBaseManager db = new JsonDataBaseManager();
Course selectedCourse = null;

try {
    ArrayList<Course> allCourses = db.getAllCourses1();

    for (Course c : allCourses) {
        if (c.getCourseId().equals(courseId)) {
            selectedCourse = c;
            break;
        }
    }

    if (selectedCourse != null) {
        CourseDialog dialog = new CourseDialog(this, selectedCourse, cu, db);
        dialog.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Course not found in database!");
    }

} catch (IOException ex) {
    JOptionPane.showMessageDialog(this, "Error loading courses: " + ex.getMessage());
    ex.printStackTrace(); // optional: log error for debugging
}


if (selectedCourse != null) {
    CourseDialog dialog = new CourseDialog(this, selectedCourse, cu, db);
    loadAllCoursesIntoTable(db);
    dialog.setVisible(true);
}
*/
        Review Revieww = new Review(this, true); // 'this' = parent frame, true = modal
    Revieww.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String u= jComboBox1.getSelectedItem().toString();
        JsonDataBaseManager db= new JsonDataBaseManager();
        if(u.equalsIgnoreCase("All courses"))
        {
          loadAllCoursesIntoTable(db);
          jTable1.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) {
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow != -1) {
                 String courseId = (String) jTable1.getValueAt(selectedRow, 0); 
                loadLessonsForCourse(courseId);
                }
            }
 });
        }                 
        if(u.equalsIgnoreCase("Pending courses"))
        {
         //JsonDataBaseManager db= new JsonDataBaseManager();
        loadPendingCoursesIntoTable(db);
        jTable1.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) {
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow != -1) {
                 String courseId = (String) jTable1.getValueAt(selectedRow, 0); 
                loadLessonsForCourse(courseId);
                }
            }
 });
        } 
    }//GEN-LAST:event_jComboBox1ActionPerformed


public class CourseDialog extends JDialog {

    public CourseDialog(JFrame parent, Course course, User currentUser, JsonDataBaseManager db) {
        super(parent, "Course Details", true); // modal dialog
        setSize(500, 400);
        setLocationRelativeTo(parent);
        setLayout(new BorderLayout());

        // ✅ Course details area
        JTextArea textArea = new JTextArea();
        textArea.setEditable(false);

        StringBuilder sb = new StringBuilder();
        sb.append("Course ID: ").append(course.getCourseId()).append("\n");
        sb.append("Title: ").append(course.getTitle()).append("\n");
        sb.append("Description: ").append(course.getDescription()).append("\n");
        sb.append("Instructor: ").append(course.getInstructorId()).append("\n");
        sb.append("Status: ").append(course.getApproval_status()).append("\n\n");

        sb.append("Students:\n");
        for (String student : course.getStudents()) {
            sb.append(" - ").append(student).append("\n");
        }

        sb.append("\nLessons:\n");
        for (Lesson lesson : course.getLessons()) {
            sb.append(" - ").append(lesson.getTitle()).append("\n");
        }

        textArea.setText(sb.toString());
        add(new JScrollPane(textArea), BorderLayout.CENTER);

        // ✅ Buttons panel
        JPanel buttonPanel = new JPanel();
        JButton approveBtn = new JButton("Approve");
        JButton rejectBtn = new JButton("Reject");

        approveBtn.addActionListener(e -> {
            try {
                course.approve(currentUser, "Approved via dialog");
                db.updateCourse(course); // persist changes
                JOptionPane.showMessageDialog(this, "Course approved!");
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error approving course: " + ex.getMessage());
            }
        });

        rejectBtn.addActionListener(e -> {
            try {
                course.reject(currentUser, "Rejected via dialog");
                db.updateCourse(course); // persist changes
                JOptionPane.showMessageDialog(this, "Course rejected!");
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error rejecting course: " + ex.getMessage());
            }
        });

        buttonPanel.add(approveBtn);
        buttonPanel.add(rejectBtn);
        add(buttonPanel, BorderLayout.SOUTH);
    }
}

    private void r()
  {
      int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a course first!");
        return;
    }
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
   
    String courseId = (String) model.getValueAt(selectedRow, 0);
    
    JsonDataBaseManager db = new JsonDataBaseManager();
    try {
        ArrayList<Course> allCourses = db.getAllCourses1();
        Course c=null;
        for (Course course : allCourses) {
            if (course.getCourseId().equals(courseId)) {
                c = course; // now you have the full object with lessons, students, history
                break;
            }
        }
        if (c != null) {
            /*JDialog dialog = new JDialog(this, "Course Details", true);
            dialog.setSize(500, 400);
            dialog.setLocationRelativeTo(this);
            dialog.setLayout(new BorderLayout());

            // Text area with details
            JTextArea textArea = new JTextArea();
            textArea.setEditable(false);
            StringBuilder sb = new StringBuilder();
            sb.append("Course ID: ").append(c.getCourseId()).append("\n");
            sb.append("Title: ").append(c.getTitle()).append("\n");
            sb.append("Description: ").append(c.getDescription()).append("\n");
            sb.append("Instructor: ").append(c.getInstructorId()).append("\n");
            sb.append("Status: ").append(c.getApproval_status()).append("\n\n");

            sb.append("Students:\n");
            for (String student : c.getStudents()) {
                sb.append(" - ").append(student).append("\n");
            }

            sb.append("\nLessons:\n");
            for (Lesson lesson : c.getLessons()) {
                sb.append(" - ").append(lesson.getTitle()).append("\n");
            }

            textArea.setText(sb.toString());
            dialog.add(new JScrollPane(textArea), BorderLayout.CENTER);

            
            JPanel buttonPanel = new JPanel();
            JButton acceptBtn = new JButton("Accept");
            JButton rejectBtn = new JButton("Reject");

            acceptBtn.addActionListener(e -> {
                c.approve(cu, courseId);
                c.getApprovalHistory().add(new ApprovalAction("APPROVED", "Admin001", "Approved via dialog"));
                try {
                    db.updateCourse(c); // you need to implement updateCourse in JsonDataBaseManager
                    JOptionPane.showMessageDialog(dialog, "Course approved!");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(dialog, "Error saving course update");
                }
                dialog.dispose();
            });

            rejectBtn.addActionListener(e -> {
                c.reject(cu, courseId);
                
                c.getApprovalHistory().add(new ApprovalAction("REJECTED", "Admin001", "Rejected via dialog"));
                try {
                    db.updateCourse(c);
                    
                    JOptionPane.showMessageDialog(dialog, "Course rejected!");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(dialog, "Error saving course update");
                }
                dialog.dispose();
            });

            buttonPanel.add(acceptBtn);
            buttonPanel.add(rejectBtn);
            dialog.add(buttonPanel, BorderLayout.SOUTH);

            dialog.setVisible(true);*/
        } else {
            JOptionPane.showMessageDialog(this, "Course not found in database!");
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error loading course details");
    }
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
