
package com.mycompany.lab8;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;



public class QuizFrame extends javax.swing.JFrame {
    private Quiz quiz;
    private int score;
     private int attemptNumber=1;
    private int currentIndex;
    private String id;
    private String courseId;
    private ArrayList<Integer> answers = new ArrayList<>();

QuizFrame(Quiz quiz,String id,String courseId)
{
    this.courseId=courseId;
    this.id=id;
    this.quiz=quiz;
    initComponents();
    
   showQuestion();
   
}
    
    public QuizFrame() {
        initComponents();
    }
    
    public void showQuestion()
{
    feedback.setText("");
    scoreLabel.setText("");
    buttonGroup1.clearSelection();
    
     ArrayList<Question> questions=quiz.getQuestions();
     ArrayList<String> options=questions.get(currentIndex).getOptions();
    text.setText(questions.get(currentIndex).getText());
    option1.setText(options.get(0));
    option2.setText(options.get(1));
    option3.setText(options.get(2));
    option4.setText(options.get(3));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        option1 = new javax.swing.JRadioButton();
        option2 = new javax.swing.JRadioButton();
        option4 = new javax.swing.JRadioButton();
        option3 = new javax.swing.JRadioButton();
        text = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        feedback = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(option1);
        option1.setText("option1");

        buttonGroup1.add(option2);
        option2.setText("jRadioButton1");

        buttonGroup1.add(option4);
        option4.setText("jRadioButton1");

        buttonGroup1.add(option3);
        option3.setText("jRadioButton1");
        option3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3ActionPerformed(evt);
            }
        });

        text.setText("jLabel1");

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        feedback.setText("jLabel1");

        scoreLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(next))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(option4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(option3)
                                    .addComponent(option1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text))
                                    .addComponent(option2))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text)
                    .addComponent(scoreLabel))
                .addGap(48, 48, 48)
                .addComponent(option1)
                .addGap(18, 18, 18)
                .addComponent(option2)
                .addGap(18, 18, 18)
                .addComponent(option3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(option4)
                    .addComponent(feedback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(next)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void option3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option3ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
       
        
        ArrayList<Question> questions=quiz.getQuestions();
        int selectedIndex=-1;
        
        if(option1.isSelected())
            selectedIndex=0;
        if(option2.isSelected())
            selectedIndex=1;
        if(option3.isSelected())
            selectedIndex=2;
        if(option4.isSelected())
            selectedIndex=3;
        if(selectedIndex==-1)
        {
            JOptionPane.showMessageDialog(this,"Cant go the next question without choosing an option");
            return;
        }
        if(selectedIndex==questions.get(currentIndex).getCorrectAnswerIndex())
        {
            score++;
            feedback.setText("Correct answer");
            answers.add(selectedIndex);
        }
        else
        {
            int y=(questions.get(currentIndex).getCorrectAnswerIndex())+1;
            feedback.setText("Wrong answer, the correct answer is option"+y);
             answers.add(selectedIndex);
        }
       
        if(currentIndex == questions.size() - 1) {
              
       JOptionPane.showMessageDialog(this,"Your Score: " + score + "/" + questions.size());
        QuizAttempt attempt=new QuizAttempt(quiz.getQuizId(),quiz.getLessonId(),score,attemptNumber,answers);
            try {
                JsonDataBaseManager.addQuizAttempt(id,attempt,quiz,courseId);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,"");
            }
            if(quiz.isPassingScore(score)){
               JOptionPane.showMessageDialog(this,"You passed the quiz and completed the lesson" );  
            Student studentFrame = new Student(id);
            studentFrame.setVisible(true);
            this.dispose();  
            studentFrame.showCoursesTab();}
            else
            {
                int choice = JOptionPane.showConfirmDialog(
        this,
        "You failed the quiz. Do you want to retry?",
        "Retry Quiz",
        JOptionPane.YES_NO_OPTION
    );

    if (choice == JOptionPane.YES_OPTION) {
        try {
            // Check retry policy before restarting
            if (!JsonDataBaseManager.canRetry(id, quiz.getQuizId(), 3)) {
                JOptionPane.showMessageDialog(this, "Retry limit reached for this quiz.");
                Student studentFrame = new Student(id);
                studentFrame.setVisible(true);
                this.dispose();
                studentFrame.showCoursesTab();
                return;
            }

            // Restart quiz frame
            QuizFrame retryFrame = new QuizFrame(quiz, id, courseId);
            retryFrame.setVisible(true);
            this.dispose();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error checking retry policy.");
        }
    } else {
        // If student chooses not to retry, return to courses
        Student studentFrame = new Student(id);
        studentFrame.setVisible(true);
        this.dispose();
        studentFrame.showCoursesTab();}}
    } 
        else {
        currentIndex++;
        if(currentIndex == questions.size() - 1) {
            next.setText("Submit");
            
        }
        Timer timer = new Timer(1000, e -> showQuestion());
    timer.setRepeats(false);
    timer.start();
        
        }
    }//GEN-LAST:event_nextActionPerformed
private void hideOptions() {
    option1.setVisible(false);
    option2.setVisible(false);
    option3.setVisible(false);
    option4.setVisible(false);
    next.setVisible(false);
    feedback.setVisible(false);
    text.setVisible(false);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel feedback;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JRadioButton option1;
    private javax.swing.JRadioButton option2;
    private javax.swing.JRadioButton option3;
    private javax.swing.JRadioButton option4;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
