/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.lab8;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author MALAK
 */
public class Review extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Review.class.getName());

    /**
     * Creates new form Review
     */
    private Course c;
    private User cu;
    public Review(java.awt.Frame parent, boolean modal)
    {
     super(parent, modal);
        initComponents();
     }
    
    public Review(java.awt.Frame parent, boolean modal,Course c,User cu) {
        super(parent, modal);
        initComponents();
        this.c=c;
        this.cu=cu;
        jTextArea1.setEditable(false);
    //jTextArea1.setText(selectedCourse.getDescription());
       loadcourse(c);
       jTextArea2.setEditable(true);
    }
    public void loadcourse(Course c)
    {
    if (c == null) {
        jTextArea1.setText("No course data available.");
        return;
    }

    StringBuilder sb = new StringBuilder();
    sb.append("Course ID: ").append(c.getCourseId()).append("\n");
    sb.append("Title: ").append(c.getTitle()).append("\n");
    sb.append("Description: ").append(c.getDescription()).append("\n");
    sb.append("Instructor ID: ").append(c.getInstructorId()).append("\n");
    sb.append("Approval Status: ").append(c.getApproval_status()).append("\n");

    // Approval history
    sb.append("Approval History:\n");
    if (c.getApprovalHistory() != null && !c.getApprovalHistory().isEmpty()) {
        for (ApprovalAction h : c.getApprovalHistory()) {
            sb.append("  - ").append(h.getAction())
              .append(" by ").append(h.getAdminId())
              .append(" at ").append(h.getTime())
              .append(" (Reason: ").append(h.getReason()).append(")\n");
        }
    } else {
        sb.append("  None\n");
    }

    // Students
    sb.append("Students: ").append(c.getStudents()).append("\n");

    // Lessons
    sb.append("Lessons:\n");
    if (c.getLessons() != null && !c.getLessons().isEmpty()) {
        for (Lesson l : c.getLessons()) {
            sb.append("  Lesson ID: ").append(l.getLessonId()).append("\n");
            sb.append("  Title: ").append(l.getTitle()).append("\n");
            sb.append("  Content: ").append(l.getContent()).append("\n");

            // Quiz details
            if (l.getQuiz() != null) {
                sb.append("    Quiz (Passing Score: ").append(l.getQuiz().getPassingScore()).append(")\n");
                for (Question q : l.getQuiz().getQuestions()) {
                    sb.append("      Q: ").append(q.getText()).append("\n");
                    sb.append("      Options: ").append(q.getOptions()).append("\n");
                   // sb.append("      Correct Index: ").append(q.getCorrectIndex()).append("\n");
                }
            }
            sb.append("\n");
        }
    } else {
        sb.append("  None\n");
    }

    // Finally set text in the read-only area
    jTextArea1.setEditable(false);
    jTextArea1.setText(sb.toString());


     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setText("Write the reason:");

        jButton1.setForeground(new java.awt.Color(0, 204, 51));
        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String reason = jTextArea2.getText().trim();
      if ("APPROVED".equals(c.getApproval_status())) {
    JOptionPane.showMessageDialog(this, "This course is already approved.");
    return;}
        
      if ("REJECTED".equals(c.getApproval_status())) {
    JOptionPane.showMessageDialog(this, "This course is already rejected.");
    return;}
      
    if (reason.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a reason before rejecting.");
        return;
    }
    c.reject(cu, reason);
    try {
       
        JsonDataBaseManager db = new JsonDataBaseManager();
        db.updateCourse(c);  
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error saving course: " + ex.getMessage());
        return;
    }
    JOptionPane.showMessageDialog(this, "Course rejected successfully!");
    dispose(); // close dialog
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String reason = jTextArea2.getText().trim();
      if ("APPROVED".equals(c.getApproval_status())) {
    JOptionPane.showMessageDialog(this, "This course is already approved.");
    return;}
        
      if ("REJECTED".equals(c.getApproval_status())) {
    JOptionPane.showMessageDialog(this, "This course is already rejected.");
    return;}
      
    if (reason.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a reason before approving.");
        return;
    }
    c.approve(cu, reason);
   // c.addApprovalHistory(new ApprovalAction("APPROVED",cu.getUserId(),reason));
    try {
       
        JsonDataBaseManager db = new JsonDataBaseManager();
        db.updateCourse(c);  
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error saving course: " + ex.getMessage());
        return;
    }
    JOptionPane.showMessageDialog(this, "Course approved successfully!");
    dispose(); // close dialog
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Review dialog = new Review(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
