/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab8;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author USER
 */
public class Student extends javax.swing.JFrame {
     private String id;
     private Studentt student;
     
       public Student()
       {};
//  private void loadCertificates() {
// try {
//        Studentt student = this.student; 
//
//        ArrayList<Certificate> certs = CertificateManager.getCertificates(student);
//        
//        DefaultTableModel certificatesModel = new DefaultTableModel();
//        certificatesModel.addColumn("student Id");
//        certificatesModel.addColumn("Certificate ID");
//        certificatesModel.addColumn("Course ID");
//        certificatesModel.addColumn("Issue Date");
//        
//        for (Certificate c : certs) {
//            certificatesModel.addRow(new Object[]{
//                c.getStudentID (),
//                c.getCertificateID(),
//                c.getCourseID(),
//                c.getIssueDate().toString()
//            });
//        }
//     certificatesTable.setModel(certificatesModel);
//
//    } catch (IOException ex) {
//        JOptionPane.showMessageDialog(this, "Error loading certificates: " + ex.getMessage());
//    }
//  }
private void loadCertificates() {
    try {
        Studentt studentToUse = this.student;
        if (studentToUse == null) {
           studentToUse = new Studentt(this.id); 
        }

        ArrayList<Certificate> certs = CertificateManager.getCertificates(studentToUse);

        DefaultTableModel certificatesModel = new DefaultTableModel(
            new Object[]{"Student ID", "Certificate ID", "Course ID", "Issue Date"}, 0
        );

        for (Certificate c : certs) {
            certificatesModel.addRow(new Object[]{
                c.getStudentID(),
                c.getCertificateID(),
                c.getCourseID(),
                c.getIssueDate() != null ? c.getIssueDate().toString() : "N/A"
            });
        }

        certificatesTable.setModel(certificatesModel);

    } catch (Exception ex) {
        ex.printStackTrace(); 
        JOptionPane.showMessageDialog(this, "Error loading certificates: " + ex.getMessage());
    }
}

      
    public Student(String id) {
         this.id=id;
        initComponents();
        try{JsonDataBaseManager dbm=new JsonDataBaseManager();
        ArrayList <Course> allCourses = new ArrayList<>();

        allCourses=dbm.loadapprovedcourses("APPROVED");

        DefaultTableModel coursesModel = new DefaultTableModel();
        coursesModel.addColumn("Course ID");
        coursesModel.addColumn("Course Name");
        coursesModel.addColumn("Instructor");
        coursesModel.addColumn("Number of Lessons");
        jTable1.setModel(coursesModel);
        for (Course c : allCourses) {
    coursesModel.addRow(new Object[]{
            c.getCourseId(),
            c.getTitle(),
            c.getInstructorId(),
            c.getLessons().size()
    });
}
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(this,"No available courses");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        enroll = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        loadBtn = new javax.swing.JButton();
        loadBtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lessonsTabel = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        content = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        certificatesTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        enroll.setText("Enroll");
        enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(enroll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(enroll)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Browse available courses", jPanel1);

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(studentsTable);

        loadBtn.setText("Search enrolled courses");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        loadBtn1.setText("Choose this course to access its lessons");
        loadBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(loadBtn)
                        .addGap(71, 71, 71)
                        .addComponent(loadBtn1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadBtn)
                    .addComponent(loadBtn1))
                .addContainerGap(373, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enrolled courses", jPanel2);

        lessonsTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(lessonsTabel);

        jButton3.setText("See content of selected lesson");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton3)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jButton3)
                .addGap(0, 363, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lessons", jPanel3);

        jButton4.setText("Take a quiz");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        content.setText("no content");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(content))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton4)))
                .addContainerGap(512, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(content)
                .addGap(46, 46, 46)
                .addComponent(jButton4)
                .addGap(0, 436, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Content", jPanel4);

        certificatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(certificatesTable);

        jButton5.setText("Download Certificate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("Load");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("View Certificate");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(81, 81, 81)
                        .addComponent(jButton6)
                        .addGap(51, 51, 51)
                        .addComponent(jButton5)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Certificates Earned", jPanel5);

        jButton1.setText("log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void showCoursesTab() {
    jTabbedPane1.setSelectedIndex(1);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        login studentFrame = new login();
        studentFrame.setVisible(true);
        
        
        this.dispose();  
        


    }//GEN-LAST:event_jButton1ActionPerformed

    private void enrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollActionPerformed
        // TODO add your handling code here:
       
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to enroll.");
            return;
        }

        Object courseId = tableModel.getValueAt(selectedRow, 0);

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to enroll course \"" + courseId +  ")?",
            "Confirm enrollment",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                JsonDataBaseManager.enrollStudentInCourse(id,(String) courseId);
                JOptionPane.showMessageDialog(this, "Course enrolled successfully.");
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Could not enroll: " + e.getMessage());
            }}
            else
            JOptionPane.showMessageDialog(this, "enrollment cancelled.");

    }//GEN-LAST:event_enrollActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        // TODO add your handling code here:4
        try{
            
        JsonDataBaseManager dbm=new JsonDataBaseManager();
        ArrayList<Course> enrolledCourses=dbm.getEnrolledCourses(id);
        
        DefaultTableModel coursesModel = new DefaultTableModel();
        coursesModel.addColumn("Course ID");
        coursesModel.addColumn("Course Name");
        coursesModel.addColumn("Instructor");
        coursesModel.addColumn("Number of Lessons");
        studentsTable.setModel(coursesModel);
        
        for (Course c : enrolledCourses) {
    coursesModel.addRow(new Object[]{
            c.getCourseId(),
            c.getTitle(),
            c.getInstructorId(),
            c.getLessons().size()});
        }
        }
        catch(Exception e)
                {
                JOptionPane.showMessageDialog(this,"No courses found for this student");
                }
    }//GEN-LAST:event_loadBtnActionPerformed

    private void loadBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtn1ActionPerformed
        // TODO add your handling code here:
         int selectedRow = studentsTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to acess its lessons .");
            return;
        }
        try{
        ArrayList<Course> enrolledCourses=JsonDataBaseManager.getEnrolledCourses(id);
        
        Object courseId = studentsTable.getValueAt(selectedRow, 0);
        HashMap<String, ArrayList<String>> progress = JsonDataBaseManager.getUserProgress(id);
        
         ArrayList<String> completedLessons = progress.containsKey((String)courseId)
                    ? progress.get((String)courseId)
                    : new ArrayList<>();
         
        for(Course c:enrolledCourses)
        {
            if(c.getCourseId().equals(courseId))
            {
                jTabbedPane1.setSelectedIndex(2);  
                ArrayList<Lesson> lessons=c.getLessons();
                
                 
        DefaultTableModel lessonsModel = new DefaultTableModel();
        lessonsModel.addColumn("lesson ID");
        lessonsModel.addColumn("lesson title");
        lessonsModel.addColumn("lesson content");
        lessonsModel.addColumn("Completed");
        lessonsTabel.setModel(lessonsModel);
        
        for (Lesson l : lessons) {
            boolean isCompleted = completedLessons.contains(l.getLessonId());
    lessonsModel.addRow(new Object[]{
            l.getLessonId(),
            l.getTitle(),
            l.getContent(), isCompleted ? "Yes" : "No"
           });
        }
             
            }
        }
       
        
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(this,"No courses found for this student");}
        
    }//GEN-LAST:event_loadBtn1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow=lessonsTabel.getSelectedRow();
         if(selectedRow==-1)
        {
            JOptionPane.showMessageDialog(this,"Please select a lesson to show its content");
            return;
        }
        int selectedrow=studentsTable.getSelectedRow();
    
        Object courseId=studentsTable.getValueAt(selectedrow, 0);
        Object lessonId=lessonsTabel.getValueAt(selectedRow, 0);
        try{
        ArrayList<Course> courses=JsonDataBaseManager.getEnrolledCourses(id);
        for(Course c:courses)
        {
            if(c.getCourseId().equals((String)courseId))
            {
               ArrayList<Lesson> lessons= c.getLessons();
               for(Lesson l:lessons)
               {
                   if(l.getLessonId().equals((String)lessonId))
                   {
                      
                        jTabbedPane1.setSelectedIndex(3);
                        content.setText(l.getContent());
                       break;
                   }
               }
            }
        }
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(this,"No courses found for this student");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(content.getText().equals("no content"))
        {
             JOptionPane.showMessageDialog(this,"Please select a lesson that has content");
            return;
        }
        else
        {
           
            int selectedRow=lessonsTabel.getSelectedRow();
             int selectedrow=studentsTable.getSelectedRow();
             
    if (selectedRow == -1 || selectedrow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a course and a lesson");
    return;
}
    
        Object courseId1=studentsTable.getValueAt(selectedrow, 0);
        String courseId = courseId1.toString().trim();
        
        Object lessonId1=lessonsTabel.getValueAt(selectedRow, 0);
        String lessonId = lessonId1.toString().trim();
        
        
        try{
           
        ArrayList<Course> courses=JsonDataBaseManager.getEnrolledCourses(id);
        for(Course c:courses)
            if(c.getCourseId().trim().equals(courseId))
            {
               ArrayList<Lesson> lessons= c.getLessons();
               for(Lesson l:lessons)
                   if(l.getLessonId().trim().equals(lessonId))
                   {
                       
                       if (l.getQuiz() == null ) {
            JOptionPane.showMessageDialog(this, "This lesson has no quiz!");
            return;
}
                       QuizFrame frame=new QuizFrame(l.getQuiz(),id,courseId);
                            frame.setVisible(true);
                            this.dispose(); 
                            return; 
                   }
            }
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(this,"No courses found for this student");
        }
           
        }
       
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
  
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loadCertificates();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    int selectedRow = certificatesTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a certificate.");
        return;
    }

    String certId = certificatesTable.getValueAt(selectedRow, 0).toString();
    String courseId = certificatesTable.getValueAt(selectedRow, 1).toString();
    String issueDate = certificatesTable.getValueAt(selectedRow, 2).toString();

    String content = "📜Certificate of Completion\n\n" +
                     "Certificate ID: " + certId + "\n" +
                     "Course ID: " + courseId + "\n" +
                     "Student ID: " + id + "\n" +
                     "Issue Date: " + issueDate;

    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setSelectedFile(new File("Certificate_" + certId + ".txt"));
    int option = fileChooser.showSaveDialog(this);

    if (option == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        try (FileWriter writer = new FileWriter(file)) {
            writer.write(content);
            JOptionPane.showMessageDialog(this, "Certificate saved successfully.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error saving certificate: " + ex.getMessage());
        }
    }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:                                                 
    int selectedRow = certificatesTable.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a certificate.");
    return;
}

String certId = certificatesTable.getValueAt(selectedRow, 0).toString();
String courseId = certificatesTable.getValueAt(selectedRow, 1).toString();
String issueDate = certificatesTable.getValueAt(selectedRow, 2).toString();

String content = "📜 Certificate of Completion 📜\n\n" +
                 "Certificate ID: " + certId + "\n" +
                 "Course ID: " + courseId + "\n" +
                 "Student ID: " + id + "\n" +
                 "Issue Date: " + issueDate;

JTextArea textArea = new JTextArea(content);
textArea.setEditable(false);
textArea.setFont(new Font("Monospaced", Font.PLAIN, 14));
JScrollPane scrollPane = new JScrollPane(textArea);

JOptionPane.showMessageDialog(this, scrollPane, "View Certificate", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable certificatesTable;
    private javax.swing.JLabel content;
    private javax.swing.JButton enroll;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable lessonsTabel;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton loadBtn1;
    private javax.swing.JTable studentsTable;
    // End of variables declaration//GEN-END:variables
}
